### ISSUE TITLE
books

### ISSUE THREAD

**Issue by muratananaho** [enpitut2017/kakei_gakuen#111]
![2017-08-07 16 39 19](https://user-images.githubusercontent.com/27848816/29016838-0ea7f100-7b8f-11e7-9b60-6a010f919877.png)
違う年度や月の同じ日同じ月が連続すると消える

**Comment by tomoya-paseri** [comment]
もともとページネーションで10件づつ取得して表示する設定なのでページネーションを使わない方法で実装しようとすると多分消えます。

**Comment by tomoya-paseri** [comment]
ページネーションの設定を消したので多分治ったと思う
が、このままだと大量に表示されてしまうので修正します。
