### ISSUE TITLE
他の人の購入アイテムも表示される

### ISSUE THREAD

**Issue by chiemi627** [enpitut2017/kakei_gakuen#113]
使ってみました！

* 買ったものリストが全員分の買ったものリストになっています。
* 他の人が買ったものを編集することができます。

これは仕様？

**Comment by tomoya-paseri** [comment]
ご確認ありがとうございます。
どちらともバグです。すべて修正いたしました。

**Comment by muratananaho** [comment]
booksはまだみんなの購入品が出てきますね
