### ISSUE TITLE
link_toのpathの書き方

### ISSUE THREAD

**Issue by KatsuyaAkasaka** [enpitut2017/kakei_gakuen#14]
```
rails routes
```
して、行きたいアクションを探して名前( = name)をメモって
```
<%= link_to '名前', name_path %>
```

**Comment by tomoya-paseri** [comment]
routes内で
get 'controller名/action名'
とかくとroutingにpathが追加されます

例えば
get 'static_page/index'
と書くと
static_page_index_pathが使えるようになります
