### ISSUE TITLE
音声入力に失敗しました

### ISSUE THREAD

**Issue by chiemi627** [enpitut2017/kakei_gakuen#231]
## 状況
* 録音開始ボタンを押して「ジュース 120円」と言いましたが何も反応がありませんでした。

## 環境
* iPhone 6S
* ブラウザ：Chrome

## 希望
* 「録音開始」よりは「音声入力」の方がわかりやすかったです
* 音声入力を始めたら音声入力していることがわかる表示があると嬉しいです

**Comment by kobya4** [comment]
・iPhone版のChromeブラウザは音声入力に対応していません
　→ ネイティブアプリの開発で対応します
・非対応ブラウザではモーダルが出ます
・ボタンの表示を「音声入力」に変更し入力中は表示を変更するようにしました
