### ISSUE TITLE
「用途」に絵文字を使うとエラーが発生する

### ISSUE THREAD

**Issue by shuuji3** [enpitut2017/kakei_gakuen#236]
## 状況
- 「用途」に「りんご🍎」と絵文字を入力すると、500エラーが発生してしまいました。
- また、エラーが発生したのにポイントが+10されてしまいました。

<img width="500" alt="2017-11-27 17 05 19" src="https://user-images.githubusercontent.com/1425259/33256832-24bcb150-d397-11e7-989c-7a813ebc5c2a.png">

## 環境
- OS: MacOS High Sierra
- ブラウザ: Google Chrome 最新版

## 希望
- 絵文字が好きなので、できたら使いたいです。
- 難しければ、「使えない文字が含まれています」というようなわかりやすいエラー表示をしてほしかったです。

**Comment by tomoya-paseri** [comment]
ご報告ありがとうございます。
携帯からご利用の方もいますので絵文字を使えるように修正いたしました。
是非ご利用ください

**Comment by shuuji3** [comment]
対応ありがとうございます。無事に絵文字を使うことができました。
