### ISSUE TITLE
ゲーム性について

### ISSUE THREAD

**Issue by MinamiKaori** [enpitut2017/kakei_gakuen#31]
# ゲーム仕様案

## 前提として
 - キャラクターは静止画
 - 経験値　当日のデータ入力　>　過去のデータ入力
 - （例：（今日7/7）7/7にかったものを入力したときの経験値の量 > 7/6以前にかったものを入力したときの経験値の量）
 - 過去のデータになればなるほど経験値の量が少ない

## キャラクター
<dl>
<dt>セリフ複数</dt>
<dd>通常時雑セリフ(例：やっほー)</dd>
<dd>データ追加時セリフ（例：記録できてえらいじゃん）</dd>
<dd>一定期間データを追加していないときのセリフ（例：最近記録してなくない・・？）</dd>
<dd>数日間データの記録を続けているときのセリフ（例：毎日続けててえらいねー）</dd>
<dt>キャラクタータイプ複数</dt>
<dd>女の子</dd>
<dd>男の子</dd>
<dd>ケモノ</dd>
<dd>植物</dd>
</dl>

## 経験値・レベル
<dl>
<dt>1. 経験値をためて、一定の経験値でレベルアップ</dt>
<dd>一定レベルで進化（流れとしてはポケモンみたいな感じ）</dd>
<dd>レベルによって次レベルアップに必要な経験値が増えてく</dd>
<dd>初期選択キャラクターによって経験値上昇率が変わるなど</dd>
<dt>2. 経験値をためて、経験値を消費して進化（ガチャ的要素）（この場合経験値と呼ぶのは正しくない）</dt>
<dd>進化ごとにレベルアップ</dd>
<dt>経験値の上がり方</dt>
<dd>連続でデータを追加すると経験値大幅アップ</dd>
<dd>GPSで端末の場所を取得して、お金を使いそうな場所（例：スーパー、コンビニとか）にいた時間から一定時間は経験値大幅アップ</dd>
</dl>

## 進化
<dl>
<dt>レベルアップによる進化の場合</dt>
<dd>通常進化</dd>
<dd>データ中の多いカテゴリによって進化分岐</dd>
<dd>アイテムによって進化分岐</dd>
<dd>セリフ解禁で進化分岐</dd>
<dd>進化の優先順位?</dd>
</dl>

## アイテム
<dl>
<dt>アイテム</dt>
<dd>一定期間経験値大幅アップ</dd>
<dd>特定の進化に必要なアイテム（例：かみなりのいし）</dd>
<dd>キャラクターの衣装アイテム</dd>
<dt>アイテム入手方法</dt>
<dd>課金</dd>
<dd>データ入力時にときどき入手できる</dd>
</dl>

**Comment by Hassaku-kun** [comment]
簡易版も欲しいですね

**Comment by MinamiKaori** [comment]
# 夏合宿中に最低限実装するところ
 - 進化段階は3
 - キャラクターは女の子のみ
 - 一定の経験値でレベルアップ
 - レベルアップ進化
 - 通常進化のみ
# 夏合宿中に実装できるとうれしいところ
 - 通常時雑セリフ
 - データ入力時セリフ

**Comment by Hassaku-kun** [comment]
経験値やレベルの具体的な数値変化等があると良いかも

**Comment by MinamiKaori** [comment]
## 経験値数値
 - レベルは1から始まります
 - レベル1 -> レベル2     |  8 経験値    |
 - レベル2 -> レベル3    |  11 経験値   |
 - レベル3 -> レベル4    |  15 経験値  |
 - レベル4 -> レベル5    |  21 経験値  |  進化
 - レベル5 -> レベル6    |  26 経験値 |
 - レベル7 -> レベル8    |  32 経験値  |
 - レベル9 -> レベル10  |  40 経験値  |  進化

とりあえず

**Comment by MinamiKaori** [comment]
ログインボーナス

**Comment by kobya4** [comment]
## 夏合宿中の案
- キャラクタ  
一人だけ
- 衣装・髪型解放
一枚絵を3枚用意して、Lv1 ~ 3という形で変化させる  
(秋ではキャラクタを複数から選択し、使い続けることで髪型や服装(パーツ単位で素材を作る)が開放されていく)

**Comment by tomoya-paseri** [comment]
現在の計算方法
max10点の減点方式
遅れた日数だけ引かれていく
どんなにひどくても0いかにはならない
