### ISSUE TITLE
https://が抜けてる

### ISSUE THREAD

**Issue by KatsuyaAkasaka** [enpitut2017/kakei_gakuen#340]
https://github.com/enpitut2017/kakei_gakuen/blob/f0124aff3a4782f3537be66c7ae7d677846d47bc/app/views/layouts/application.html.erb#L58

広告が表示されない原因がこれかわからないけど少なくとも間違っている気がするので
src="https://adm.shinobi.jp/o/75faea35dab0bc9e0c61c75bd1a73f4f" だよね

**Comment by KatsuyaAkasaka** [comment]
ずっと待ってると(8sくらい)広告出てきたので問題なさそう、勘違いでした。
でも気になったのでまだcloseしておきません。

**Comment by k0bya4** [comment]
記法として存在している
