### ISSUE TITLE
userのホーム画面へ書くページから戻りたい

### ISSUE THREAD

**Issue by muratananaho** [enpitut2017/kakei_gakuen#42]
indexからは一時的に@book.first.userで戻っていますが
bookのnew画面はそれじゃできないので戻るボタンでそいやしないといけない感じになっている
ログイン機能もついたので各ページちゃんとそのユーザーの情報どおり遷移できるようにするのは明後日(?)に持ち越し

**Comment by kobya4** [comment]
✔
