### ISSUE TITLE
ヘッダーとフッダー直して欲しい話

### ISSUE THREAD

**Issue by MinamiKaori** [enpitut2017/kakei_gakuen#46]
ヘッダーのログインボタンが、ウィンドウサイズを小さくした時にロゴのすぐ横に来てしまうので直してほしく
![2017-08-04 16 27 04](https://user-images.githubusercontent.com/27848842/28958563-c9519e62-7931-11e7-8fae-2e3435d924c1.png)

**Comment by MinamiKaori** [comment]
あと、ヘッダーが本体にかぶってきてしまうのでマージンあたりも見直しましょう

**Comment by muratananaho** [comment]
footerにより消える領域があるのでそれも

**Comment by Hassaku-kun** [comment]
footerで隠れるのははNewボタン側のせいで，footerの下の領域は修正しました．
headerはまだ不明

**Comment by tomoya-paseri** [comment]
俺の使ってるやつがフルハイビジョンで出せないのが悪いけどフルハイじゃないとfooterでnewとかindexが消えますね
