### ISSUE TITLE
いい感じにボタンが押せるCSS

### ISSUE THREAD

**Issue by Hassaku-kun** [enpitut2017/kakei_gakuen#47]
いい感じにボタンライクになるやつです
キャラを押したりに使えるかも

btn{
  position: absolute;
  top: 0;
  bottom: 0;
  right: 0;
  left: 0;
  margin: auto;
  width: 75%;
}
#btn:hover{
  width: 80%;
}
#btn:active{
  width: 72%;
}

**Comment by kobya4** [comment]
あとで試してみましょう
