### ISSUE TITLE
api接続について

### ISSUE THREAD

**Issue by tomoya-paseri** [enpitut2017/kakei_gakuen#50]
まったく急ぎではないうえ、おそらく秋にやればいい案件です。
api接続が簡単に作成できそうなので一応書いておきます。

api接続をしてiphoneなどのアプリとやり取りができそうです。

もしこれをやりたい場合は
・/api/またはapi.のサブドメインで接続された場合はjsonで返す。
・ユーザー認証のアクセストークンを作成し、それを受け渡ししてデータのやり取りする。

この二つがとりあえず必要になります。

**Comment by Hassaku-kun** [comment]
解決！
