### ISSUE TITLE
購入物品の入力時に日付入力が必要？

### ISSUE THREAD

**Issue by Hassaku-kun** [enpitut2017/kakei_gakuen#52]
今の仕様だとタイムスタンプの作成日時を使っているけど，後日入力することやその日中の入力を推奨することなどを考えるとタイムスタンプとは別に日付入力させる必要があるかも．

**Comment by MinamiKaori** [comment]
経験値のことも考えるとかなり必要っぽい

**Comment by kobya4** [comment]
datepickerを使うことにした
